name: Déploiement application
on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Environnement de déploiement'     
        required: true
        default: 'dev'

jobs:
  deploy-env:
    runs-on: ubuntu-latest
    steps:
    - name: Démarrage workflow
      run: echo "Démarrage du workflow sur ${{ github.ref }}"
    - name: Récupération code
      if: ${{ github.ref == "refs/heads/main"}}
      uses: actions/checkout@v4.1.1


